# Generated by Django 3.1.2 on 2020-10-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userRank',
            field=models.CharField(default='Basic', max_length=10),
        ),
    ]
